name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'type/enhancement'
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'type/bug'
      - 'bug'
      - 'fix'
  - title: 'ğŸ“š Documentation'
    labels:
      - 'area/docs'
      - 'documentation'
  - title: 'ğŸ§° Tools'
    labels:
      - 'area/tools'
      - 'tooling'
  - title: 'ğŸ”Œ Plugin'
    labels:
      - 'area/plugin'
  - title: 'ğŸ§ª Testing'
    labels:
      - 'area/testing'
      - 'test'
  - title: 'ğŸ“¦ Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'type/bug'
      - 'bug'
  default: patch
template: |
  ## Changes in this Release

  $CHANGES
